### ISSUE TITLE
Implement basic GET w/ a test

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/tokenserver-rs#10]
The goal here is to get some very basics of the handler built w/ an accompanying test.

- Add the GET handler responding to the `/1.0/sync/1.5` path, returning some dummy data that resembles a tokenserver 200 response for now
- Implement at least one of the 4 python [VALIDATORS](https://github.com/mozilla-services/tokenserver/blob/050ab53/tokenserver/views.py#L317): [valid_client_state](https://github.com/mozilla-services/tokenserver/blob/050ab53/tokenserver/views.py#L288) is a nice one to start with. These validators should be implemented as actix-web extractors. I'm not sure if each of these 4 would become their own individual extractors, or all live in the same extractors, or a combination of both in a meta extractor (we have one of those in syncstorage-rs)
- Implement a simple test that ensures a 200 OK response

We've discussed building out an integration test suite in Python, but I'd love to see just a basic unit test here utilizing actix-web's testing support.

**Comment by pjenvey** [comment]
>     * Implement at least one of the 4 python [VALIDATORS](https://github.com/mozilla-services/tokenserver/blob/050ab53/tokenserver/views.py#L317): [valid_client_state](https://github.com/mozilla-services/tokenserver/blob/050ab53/tokenserver/views.py#L288) is a nice one to start with.

Implementing this as an extractor would probably look something like this:

- We put all our syncstorage-rs extractors in `src/web/extractors.rs`, that's a good place for them
- This extractors module would end up w/ a new `ClientState` struct: this struct will hold the extracted & validated client_state `value` from the header, probably just as a `String`
- This `ClientState` struct will have a `impl FromRequest`. Its `from_request` method will be roughly equivalent to that [valid_client_state](https://github.com/mozilla-services/tokenserver/blob/050ab53/tokenserver/views.py#L288) code in the Python: but instead of storing the final client state value in a "validated" dict, it'll simply return a new instance of the `ClientState` struct when the value is validated. If it's not valid, it instead returns an error (later we can fix this error to render a 400 response like the Python does)
- The new GET handler will take a `ClientState` type as an argument. This causes actix-web to call the `FromRequest` automatically and hand off a successful result to the handler

**Comment by jrconlin** [comment]
Closed via #11
