### ISSUE TITLE
Break down tokenserver work for Q4

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/tokenserver-rs#19]
We'd like to finish porting the tokenserver to rust by the end of Q4.

  - Survey the remaining work
  - Break down bugs into small enough chunks and file them

**Comment by tublitzed** [comment]
@fzzzy - Instead of breaking the work down into bugs, let's get a document together with the plan so we can review as a team next week? Once we're in agreement on how to proceed, then go ahead and file bugs, but we should give some time for folks to review first (including client team).

**Comment by fzzzy** [comment]
👍 https://docs.google.com/document/d/10pwmjY1zMBzIdNpL3TV2FZXQLi2ste0Y2FQdcDyT4Ug/edit?usp=sharing

**Comment by fzzzy** [comment]
https://github.com/mozilla-services/syncstorage-rs/issues/864
https://github.com/mozilla-services/syncstorage-rs/issues/865
https://github.com/mozilla-services/syncstorage-rs/issues/866
https://github.com/mozilla-services/syncstorage-rs/issues/867
https://github.com/mozilla-services/syncstorage-rs/issues/868
